### ISSUE TITLE
Port 5000

### ISSUE THREAD

**Issue by cryptohgb** [Mrgoodwill/PRO4#2]
Dass standardmäßig Port 5000 verwendet wird, macht wahrscheinlich nicht nur bei mir Probleme. Noch kann ich es mir umschreiben, das könnte aber mühsam werden. Bitte eine bequeme Lösung finden.

**Comment by VladimirFogel** [comment]
Ich habe es auf Port 8000 geändert, haben es auch getestet, es funktioniert.

**Comment by VladimirFogel** [comment]
This issue has been resolved
